name: Tests

on:
  push:
  pull_request:

jobs:
  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  analyzer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install analyzer deps
        working-directory: ai-analyzer
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run analyzer tests
        working-directory: ai-analyzer
        run: pytest -q
